/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#3b475b",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dae2ff",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e2e4",
        "on-surface-variant": "#444748",
        "inverse-primary": "#c8c6c5",
        "on-background": "#191c1e",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary-container": "#78849a",
        "primary": "#000000",
        "outline-variant": "#c4c7c7",
        "on-primary-container": "#858383",
        "surface-container-high": "#e7e8ea",
        "secondary-fixed-dim": "#b2c5ff",
        "surface-container-highest": "#e1e2e4",
        "secondary": "#0453cd",
        "primary-container": "#1c1b1b",
        "error": "#ba1a1a",
        "outline": "#747878",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadc",
        "surface-container-low": "#f3f4f6",
        "primary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#2e3132",
        "background": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#bbc7de",
        "surface-tint": "#5f5e5e",
        "tertiary-container": "#101c2d",
        "surface-container": "#edeef0",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#101c2d",
        "on-surface": "#191c1e",
        "surface-bright": "#f8f9fb",
        "tertiary-fixed": "#d7e3fb",
        "primary-fixed": "#e5e2e1",
        "surface": "#f8f9fb",
        "on-secondary-fixed": "#001848",
        "on-primary-fixed": "#1c1b1b",
        "tertiary": "#000000",
        "on-secondary-fixed-variant": "#0040a2",
        "secondary-container": "#356ee7",
        "on-primary-fixed-variant": "#474746",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "base": "4px",
        "md": "24px",
        "xl": "80px",
        "lg": "48px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "xs": "8px",
        "sm": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "title-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
